export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_DASHBOARD_DETAILS = "GET_DASHBOARD_DETAILS";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const CLEAR_DASHBOARD_DETAILS = "CLEAR_DASHBOARD_DETAILS";

export const GET_POSTS = "GET_POSTS";
export const POSTS_LOADING = "POSTS_LOADING";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const GET_COMMUNITY_POSTS = "GET_COMMUNITY_POSTS";
export const COMMUNITY_POSTS_LOADING = "COMMUNITY_POSTS_LOADING";

export const GET_COMMENTS = "GET_COMMENTS";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS";

export const SEARCH_REDIRECT = "SEARCH_REDIRECT";
export const RESET_SEARCH_REDIRECT = "RESET_SEARCH_REDIRECT";

export const USER_LOGOUT = "USER_LOGOUT";
export const SET_JWT_TOKEN = "SET_JWT_TOKEN";
export const SET_INVITE_UPDATED = "SET_INVITE_UPDATED";

export const GET_MESSAGE = "GET_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";

export const SET_COMMUNITY_ID = "SET_COMMUNITY_ID";
export const SET_COMMUNITY_NAME = "SET_COMMUNITY_NAME";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_COMMUNITY = "GET_USER_COMMUNITY";

export const USER_PROFILE_GET = 'USER_PROFILE_GET';
export const USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE';
export const USER_IMAGE_GET = 'USER_IMAGE_GET';
export const USER_IMAGE_UPDATE = 'USER_IMAGE_UPDATE';