export const GET_ERRORS ='GET_ERRORS';
export const SET_CURRENT_USER ='SET_CURRENT_USER';

export const GET_DASHBOARD_DETAILS ='GET_DASHBOARD_DETAILS';
export const DASHBOARD_LOADING ='DASHBOARD_LOADING';
export const CLEAR_DASHBOARD_DETAILS ='CLEAR_DASHBOARD_DETAILS';


export const USER_LOGOUT ='USER_LOGOUT';
