export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_DASHBOARD_DETAILS = "GET_DASHBOARD_DETAILS";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";
export const CLEAR_DASHBOARD_DETAILS = "CLEAR_DASHBOARD_DETAILS";

export const GET_POSTS = "GET_POSTS";
export const POSTS_LOADING = "POSTS_LOADING";
export const CLEAR_POSTS = "CLEAR_POSTS";

export const GET_COMMENTS ='GET_COMMENTS';
export const COMMENTS_LOADING ='COMMENTS_LOADING';
export const CLEAR_COMMENTS ='CLEAR_COMMENTS';

export const SEARCH_REDIRECT = 'SEARCH_REDIRECT';
export const RESET_SEARCH_REDIRECT = 'RESET_SEARCH_REDIRECT';

export const USER_LOGOUT = "USER_LOGOUT";
export const SET_JWT_TOKEN = "SET_JWT_TOKEN";
export const SET_INVITE_UPDATED = "SET_INVITE_UPDATED";

